---
- name: Wait for the virtual machine to shutdown
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    name: "{{ vm_name }}"
    state: shutdown-guest
    state_change_timeout: 200
    validate_certs: no
  delegate_to: localhost
  register: deploy

# tasks file for vm_build_bracknell
- name: Remove "{{ vm_name }}"
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: absent
  delegate_to: localhost
  register: facts
  tags:
    - remove_vm
